#!/root/ansible/myansible/bin/ansible-playbook
- name: Installing WebServer
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  vars:
    custom_var : 123abc

  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: present
      notify:
        - Ensure Apache is Running
       
    - name: Updating Index HTML file
      template:
        src: index.html.j2
        dest: /usr/share/httpd/noindex/index.html
      notify:
        - Ensure Apache restart 

  handlers:
    - name: Ensure Apache is Running
      service:
        name: httpd
        state: started

    - name: Ensure Apache restart
      service:
        name: httpd
        state: restarted