#!/root/ansible/myansible/bin/ansible-playbook
- name: Installing WebServer
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: latest
    - name: Ensure Apache is Running
      service:
        name: httpd
        state: started