#!/root/ansible/myansible/bin/ansible-playbook
- name: Introduction Ansible Playbooks
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Checking Connection via Ping
      ping:

    - name: Uninstall Apache WebServer
      yum:
        name: httpd
        state: absent 