#!/root/ansible/myansible/bin/ansible-playbook
- name: This is Overview of Ansible Register and Set_Fact
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Retrive Installed Shell Version
      shell: "bash --version"
      register: bash_ver

    - set_fact:
        bash_version: "{{bash_ver.stdout_lines[0].split()[3]}}"
    
    - debug:
        var: bash_version 