#!/root/ansible/myansible/bin/ansible-playbook
- name: Including Include Playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Play 1 - Task 1
      debug:
        msg: "Play 1 - Task 1"

- include: play2.yml